### ISSUE TITLE
DTypeWarning Error using playerid_lookup()

### ISSUE THREAD

**Issue by jfreynolds** [jldbc/pybaseball#10]
Apologies for another issue. I'm getting this following error when using `playerid_lookup(last, first)` function fairly consistently:

`sys:1: DtypeWarning: Columns (8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.`

This issue seems to occur when reading the `people.csv` file into a dataframe. The dtypes are inconsistent for some column(s) within that file and I'm not sure where. 

There are two fixes and I wanted to see which was preferred. The first option is to specify the dtypes for each column in the file so that there is no guessing involved and/or reading the entire file into memory before allocating and assigning a dataframe. The second option is to specify the low_memory argument to `pandas.read_csv()` to be False (default is True). I'm finding conflicted statements about the argument, some saying it is deprecated and others that say it isn't. If it is deprecated, it will just suppress the error; however, if it isn't deprecated, then it will use more memory in order to read all tuples of a column into memory to validate a type.

Is the larger memory footprint at runtime satisfactory or should the dtypes be specified for all the columns in the Chadwick Register?

**Comment by jldbc** [comment]
The lower memory footprint is ideal if a solution with using dtypes will work. 

It looks like only columns 8, 9, and 10 cause the warning. I think we could get away with specifying `dtype={'key_sr_nfl': object, 'key_sr_nba': object, 'key_sr_nhl': object}` in read_csv without going through the other columns.
