### ISSUE TITLE
Non-issue/non-PR communication

### ISSUE THREAD

**Issue by TheCleric** [jldbc/pybaseball#119]
I've been submitting a lot of PRs lately (too many?) and I feel like some of them could have been cleared up with me asking some questions like "Would anyone mind if...?" or "Does anyone think this is a good idea?".

I don't really want to clog up our issues with these sorts of questions, so I was wondering what kind of interest other devs would have in doing some non-Github communications for quick questions/asides. Anything important could be brought into Github, but would keep this repo clean from unimportant discussions.

I initially thought email, but that can get clunky. I'm thinking IRC chat would work, and have added a channel on Freenode (an open source IRC server, also where python and linux have their IRC channels).

If that's okay here it is:
https://webchat.freenode.net/#pybaseball

Respond to this if anyone has alternative suggestions or if anyone thinks this is a bad idea.

**Comment by schorrm** [comment]
I don't do IRC, so it doesn't strike me as great. I'm happy to have a discussion group, I'd just prefer it on a medium I might actually see.

**Comment by TheCleric** [comment]
> I don't do IRC, so it doesn't strike me as great. I'm happy to have a discussion group, I'd just prefer it on a medium I might actually see.

Completely understand. What would be preferable for you?

**Comment by schorrm** [comment]
Email, WhatsApp, FBM, whatever, just something that I already use

**Comment by schorrm** [comment]
My main message services are FB and WhatsApp. Ppl can also PM me on Twitter if you like.

**Comment by TheCleric** [comment]
I don't hand out my social media handles publicly, but if someone wants to email me: adamweeden@gmail.com, and I can send you them via that.

**Comment by kmedved** [comment]
A few other packages I've seen use Slack for this sort of thing (e.g. Ray and Tabnet both have useful slack discussions, for issues which don't rise to the level of a Github issue). Not sure if you guys Slack, but wanted to throw that out there.

**Comment by TheCleric** [comment]
> A few other packages I've seen use Slack for this sort of thing (e.g. Ray and Tabnet both have useful slack discussions, for issues which don't rise to the level of a Github issue). Not sure if you guys Slack, but wanted to throw that out there.

Yeah that would work for me as well as I'm on Slack all day for work anyway. 😆 

Discord would also work for me, but I know some folks in the open source world really don't like it as it's closed source and they've been known to monitor communication.

**Comment by bdilday** [comment]
yeah, slack seems ideal

**Comment by kmedved** [comment]
Obviously only makes sense if it's something @schorrm uses however.

**Comment by schorrm** [comment]
I don't use it often, but I have it on my phone, so it wouldn't be a hassle

**Comment by TheCleric** [comment]
Cool I'll set it up.

**Comment by TheCleric** [comment]
https://join.slack.com/t/newworkspace-gkx5592/shared_invite/zt-hipftv5t-Z591hZ3eRPI1uGjuPfPdhA

**Comment by TheCleric** [comment]
@jldbc we'd love to have you join as well. I would not anyone to make any decisions about the future of the library without your consideration or input.
