### ISSUE TITLE
Issues with standardizations of names between functions

### ISSUE THREAD

**Issue by Am3ra** [jldbc/pybaseball#156]
The problem here is simple: There are teams like the LA Angels whose acronym in bbref is `LAA`, while in retrosheet and its functions it's `ANA`.

I created the following structures to deal with this problem:

``` python
bbref_current_teams = ["ARI","ATL","BAL","BOS","CHC","CHW","CIN","CLE","COL",
                      "DET","HOU","KCR","LAA","LAD","MIA","MIL","MIN","NYM",
                      "NYY","OAK","PHI","PIT","SDP","SEA","SFG","STL","TBR",
                       "TEX","TOR","WSN"]

retrosheet_current_teams = ["ANA","BAL","BOS","CHA","CLE","DET","HOU","KCA",
                            "MIN","NYA","OAK","SEA","TBA","TEX","TOR","ARI",
                            "ATL","CHN","CIN","COL","LAN","MIA","MIL","NYN",
                            "PHI","PIT","SDN","SFN","SLN","WAS"]

bbref_to_retrosheet = {"ARI":"ARI","ATL":"ATL","BAL":"BAL","BOS":"BOS","CHC":"CHN","CHW":"CHA","CIN":"CIN","CLE":"CLE","COL":"COL",
                      "DET":"DET","HOU":"HOU","KCR":"KCA","LAA":"ANA","LAD":"LAN","MIA":"MIA","MIL":"MIL","MIN":"MIN","NYM":"NYN",
                      "NYY":"NYA","OAK":"OAK","PHI":"PHI","PIT":"PIT","SDP":"SDN","SEA":"SEA","SFG":"SFN","STL":"SLN","TBR":"TBA",
                       "TEX":"TEX","TOR":"TOR","WSN":"WAS"}

retrosheet_to_bbref = {v: k for k, v in bbref_to_retrosheet.items()} 
```

I was wondering if people would be interested in including this in the package, or if something similar already exists? Additionally, this helps to iterate over teams. 

Would like to know your opinions.

**Comment by TheCleric** [comment]
This already exists in the lahman teams data to my knowledge. There should be a fields for `teamIDBR` and `teamIDretro `

**Comment by schorrm** [comment]
This is the sort of thing that could make a **lot** of sense in a `pybaseball.constants`

**Comment by TheCleric** [comment]
@schorrm or we could modify `teamid_lookup.py` to not be specific to Fangraphs and include these other ids as well. Just depends if we want to make it easier, or let Lahman worry about that data.

**Comment by Am3ra** [comment]
@schorrm in particular, and everyone in general, what other similar utilities would you appreciate?

I think these are enough on theri own to merit a PR,  but I wonder if more could be added as well.

@TheCleric , The only thing that worries me is the resulting data, as long as it all comes out with standardized names that's cool.

**Comment by TheCleric** [comment]
@Am3ra check out my PR #159 and see if this would accomplish what you were looking for.

**Comment by TheCleric** [comment]
This should now work via the teamid_lookup per #159

**Comment by schorrm** [comment]
@TheCleric can we close this?

**Comment by TheCleric** [comment]
I would say so, but I was leaving it up to @Am3ra to sign off on to ensure I met the spirit of his request.

**Comment by Am3ra** [comment]
Thanks for the patience guys. I'll try to check it out in my project later today, and will close the issue.
