### ISSUE TITLE
2020 WS Game 6 doesn't seem to import from StatCast

### ISSUE THREAD

**Issue by tjburch** [jldbc/pybaseball#166]
StatCast pulls for game 6 don't seem to yield any results for some reason:

```
>>> from pybaseball import statcast
>>> print("Game 5: ",len(statcast("2020-10-25","2020-10-25")))
Game 5:  292
>>> #just check 10/27
>>> print("Game 6: ",len(statcast("2020-10-27","2020-10-27")))
Game 6:  0
>>> #check surrounding dates?
>>> print("Game 6: ",len(statcast("2020-10-26","2020-10-28")))
Game 6:  0
```

However it does seem to be on baseball savant: https://baseballsavant.mlb.com/gamefeed?game_pk=635886&game_date=2020-10-27

**Comment by schorrm** [comment]
I think it's an upstream problem -- thru their search on the website --
https://baseballsavant.mlb.com/statcast_search?hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7C&hfC=&hfSea=2020%7C&hfSit=&player_type=pitcher&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=2020-10-26&game_date_lt=2020-09-30&hfInfield=&team=&position=&hfOutfield=&hfRO=&home_road=&hfFlag=&hfPull=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=api_h_launch_speed&sort_order=desc&min_pas=0#results

**Comment by tjburch** [comment]
Strange! Sorry for the excess issue

**Comment by schorrm** [comment]
I noted the same thing happening to me, I wanted to check the spin rates
