### ISSUE TITLE
Spraychart doesn't render outside of Jupyter Environments

### ISSUE THREAD

**Issue by tjburch** [jldbc/pybaseball#172]
The spraychart function seems to work fine in a Jupyter notebook:

<img width="769" alt="Screen Shot 2020-12-20 at 1 33 23 PM" src="https://user-images.githubusercontent.com/16945590/102723052-08e5bc00-42cb-11eb-9aba-9c7ddfd1c134.png">

However, from terminal, 

```
>>> from pybaseball import spraychart, statcast_batter
>>> data = statcast_batter("2019-05-01", "2019-05-10", 514888)
Gathering Player Data
>>> sub_data = data[data["home_team"]=="HOU"]
>>> spraychart(sub_data, "astros", title="Jose Altuve: May-June 2019").show()
```

Gives a specification error:

<img width="1013" alt="Screen Shot 2020-12-20 at 1 42 23 PM" src="https://user-images.githubusercontent.com/16945590/102723084-49ddd080-42cb-11eb-99b8-8480e704efc9.png">

**Comment by tjburch** [comment]
(brought up by @E_Mart97  - https://twitter.com/E_Mart97/status/1340721294317260800)

**Comment by andersonfrailey** [comment]
Interesting. Thanks for opening this issue up. I'll take a look at it tonight
