### ISSUE TITLE
Want to get involved; q about season_stats

### ISSUE THREAD

**Issue by cro1100** [jldbc/pybaseball#178]
Hi, I have 2 things:
1.) I'm a newbie to data engineering, but I'd like to get involved.  As I look at the documentation, I understand how it works, but as I try to dig into the code, I don't think I can see anything.  Is there something which needs to be done for me to see more of this?  What would you like from me?
2.) I'm working on a class project and noticing when I pull season stats, it only pulls "qualified players".  I'd love to be able to grab data based on a lower limit of innings/plate appearances and am wondering if there's a way to pull fangraphs data using that additional filter.  Is there a way to do this?

I love what has been done here and hope I can add something to the project!  Thanks!

**Comment by schorrm** [comment]
For 2: Look at the docs, the `qual` keyword is what you want.
https://github.com/jldbc/pybaseball/blob/master/docs/fangraphs.md

Re 1 -- I would suggest you try and work with familiarizing yourself with Pandas, and then move on from there. If you can do analysis in Pandas, you can probably do the preprocessing stuff (also in Pandas) that we do.

**Comment by cro1100** [comment]
So my apologies, but I'm not totally sure how to fork the code to be able
to change the qual.  Is that something I simply do with the call of
"pitching_stats"?  say for example it should be "pitching_stats(2020, 2020,
qual = 30)"?  Or is there something else I need to do?

I've got some familiarity with Pandas btw.  I'll keep trying to follow the
threads to see how I can jump in.

**Comment by schorrm** [comment]
You don't need to fork. You just need to invoke `qual=123` in the call.

**Comment by cro1100** [comment]
Excellent, just did it.  Thanks so much!
