### ISSUE TITLE
Batter handedness splits

### ISSUE THREAD

**Issue by rneu31** [jldbc/pybaseball#18]
Tossing this out as a question before I attempt to implement it...

Are one of the numerous columns returned with `betting_stats()` the platoon split? Thanks!

**Comment by jldbc** [comment]
I don't believe so. Most if not all of those metrics are defined [here](https://www.fangraphs.com/library/offense/offensive-statistics-list/) and I'm not seeing it

**Comment by jldbc** [comment]
@rneu31 did you ever make an attempt at this? I'd be interested if you've made any progress here
