### ISSUE TITLE
Splits bug

### ISSUE THREAD

**Issue by walkstew** [jldbc/pybaseball#209]
![Screen Shot 2021-04-27 at 1 59 54 PM](https://user-images.githubusercontent.com/77593250/116290068-14f1f680-a761-11eb-956e-dab0b6259cd6.png)
New to pybaseball, throwing this error when I'm putting the example in. Any thoughts or tips would be greatly appreciated!

**Comment by tjburch** [comment]
This was fixed with #206. You can install the master version of pybaseball (via cloning) or just go into the `split_stats.py` file and changing line 86 from `"overthrow_table_container"` to `"table_container"`. Should be in the next release.

**Comment by schorrm** [comment]
In about 5 minutes (once the CI updates the PyPI) just update the pybaseball thingy from there.
