### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by pfe1223** [jldbc/pybaseball#212]
Trying to install the package, but am getting the error below.

![Screen Shot 2021-05-05 at 9 27 55 PM](https://user-images.githubusercontent.com/2800013/117229331-d1def580-ade8-11eb-948f-51071a52349f.png)

**Comment by tjburch** [comment]
This could be any number of problems, generally external to pybaseball - can you pip install other packages?

What command are you using to install? It's not shown in your screenshot.

Try running `python -c "from Cython.Distutils import build_ext"`. If that throws an error, it means there's something wrong with your cython install, probably just run a `pip install --upgrade cython`. If it doesn't throw an error, my guess would be that sudo isn't picking up the right cython, see [this stackoverflow answer](https://stackoverflow.com/questions/11108461/importerror-no-module-named-cython-distutils)

**Comment by pfe1223** [comment]
I cloned the repo, changed to the appropriate directory, and typed `pip3 install -e .`. I installed `cython` but got an error about `pyarrow`. Somebody on StackOverflow suggested installing `cmake`, which I did. I am still getting an error about `pyarrow`.

![Screen Shot 2021-05-06 at 1 41 44 PM](https://user-images.githubusercontent.com/2800013/117342090-d0f1a680-ae70-11eb-87a4-e3dd5315ad2f.png)

**Comment by pfe1223** [comment]
I got it working, though more through stumbling around with `pip install` than anything. Thanks for your help.

**Comment by tjburch** [comment]
Was it something system-based? Would be nice to know if there was something off with our requirements (though I thought the ci would have caught that)

**Comment by pfe1223** [comment]
Things that I did (not sure which of these solved the issue):
* Install `cython`
* Install `cmake`
* Upgrade `pip`
* Install `pyarrow`
* Finally, `pip3 install pybaseball` worked

**Comment by tjburch** [comment]
Cool, thanks. I think this should be fine looking at `setup.py`. @schorrm, this can probably be closed.
