### ISSUE TITLE
Issue with pitcher expected stats

### ISSUE THREAD

**Issue by mileskee7** [jldbc/pybaseball#217]
I typed "from pybaseball import statcast_pitcher_expected_stats" and got an error message that said "cannot import name 'statcast_pitcher_expected_stats' from 'pybaseball.' I am very new to this, so I might have messed something up.

**Comment by cap099** [comment]
Try `from pybaseball.statcast_pitcher import statcast_pitcher_expected_stats`.  That seems to have worked for me.

**Comment by cap099** [comment]
> I typed "from pybaseball import statcast_pitcher_expected_stats" and got an error message that said "cannot import name 'statcast_pitcher_expected_stats' from 'pybaseball.' I am very new to this, so I might have messed something up.

Try `from pybaseball.statcast_pitcher import statcast_pitcher_expected_stats`  That seems to have worked for me.

**Comment by mileskee7** [comment]
That worked, thanks a lot.
