### ISSUE TITLE
Spraychart mlbstadiums.csv dimensions appear smaller than hc_x and hc_y values suggest

### ISSUE THREAD

**Issue by corguntu** [jldbc/pybaseball#224]
![photo_2021-07-26_00-28-45](https://user-images.githubusercontent.com/57296264/126939413-1dc9b1f9-03a5-4c81-88de-b4cebe2b6e8f.jpg)

```
sub_data = df_2019[df_2019['events'] == 'triple']
spraychart(sub_data, 'astros', width=700, height=700, title='minutemaid 2019 triples',colorby='launch_speed_angle')

```
Something I'm missing? max hc_x and hc_y values of triples are roughly 33% greater than the ballpark dimensions contained in mlbstadiums.csv

**Comment by schorrm** [comment]
This was @andersonfrailey's PR way back when... hm...

**Comment by schorrm** [comment]
Is it possible that this is just imputed landing -- where it _would_ land if there was no fence or something?

**Comment by bdilday** [comment]
it looks like maybe the graph you attached doesn;t correpsond to the command you showed? It looks like Fenway, not Minute Maid. Also it looks like you're plotting triples for all teams? Attached is what I get with, 
``` 
spraychart(batting_data[batting_data.home_team.str.startswith("HOU")], 'astros', width=700, height=700, title='minutemaid 2019 triples',colorby ='launch_speed_angle')
```

where `batting_data` is from [this search](https://baseballsavant.mlb.com/statcast_search?hfPT=&hfAB=triple%7C&hfGT=R%7C&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfPull=&hfC=&hfSea=2019%7C&hfSit=&player_type=batter&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=&game_date_lt=&hfInfield=&team=&position=&hfOutfield=&hfRO=&home_road=&hfFlag=&hfBBT=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=api_p_release_speed&sort_order=desc&min_pas=0#results)


![minmaid1](https://user-images.githubusercontent.com/5924783/127190877-b7976ad1-68f6-4de2-8525-1a233d18e19d.png)
