### ISSUE TITLE
statcast_sprint_speed Import Error

### ISSUE THREAD

**Issue by jgamblin** [jldbc/pybaseball#225]
I was attempting to look at the sprint speeds for this year using [this example](https://github.com/jldbc/pybaseball/blob/master/docs/statcast_running.md ) and end up getting this error:

 ```ImportError: cannot import name 'statcast_sprint_speed' from 'pybaseball' (/usr/local/lib/python3.9/site-packages/pybaseball/__init__.py)```

[My Test Jupyter Notebook is here. ](https://gist.github.com/jgamblin/0491f84a0d7fc6a50e394b3ed4692c89)

![Screen Shot 2021-07-27 at 7 50 33 AM](https://user-images.githubusercontent.com/8428124/127156446-70cfcdfb-d1e0-40fc-85b0-87c62c18b426.png)

**Comment by schorrm** [comment]
Whoopsy, idk what happened there.
For the time being, you can use:
`from pybaseball.statcast_running import statcast_sprint_speed`
@wfordh what should be happening here? Is the doc wrong or is the code wrong?

**Comment by wfordh** [comment]
Hmm I'll look into it. I know when I was testing the other statcast pieces the imports were a little different than anticipated. Without looking, either what's in the example or what @schorrm suggested should work.

**Comment by schorrm** [comment]
Fixed in #228
