### ISSUE TITLE
Issue installing on Mac

### ISSUE THREAD

**Issue by david1111039243** [jldbc/pybaseball#234]
Hi there, this is a really beginner question :) I've been using pybaseball in Google colabs and now wanted to use it in a jupyter notebook.

I've tried installing on my Mac via terminal with 
`pip3 install pybaseball==2.2.1`
and it appears to have worked.

I then have an ipynb notebook and wanted to run the code:
```
import pybaseball as pyb
data = pyb.batting_stats(2019)
```

I get an error here and attached a screenshot. I can't tell if the issue is with the pybaseball install or the new notebook. Any thoughts? Thanks so much!

<img width="648" alt="Screen Shot 2021-08-25 at 2 52 23 PM" src="https://user-images.githubusercontent.com/43319024/130848488-50f5af58-ea6d-4d2f-b998-ab9f47a444a0.png">

**Comment by schorrm** [comment]
I would recommend installing based on the GitHub, that'll be a better bet than using the pip releases

**Comment by schorrm** [comment]
Which Python version is this?

**Comment by david1111039243** [comment]
Tried re-installing and it worked. Cheers!
