### ISSUE TITLE
Not all players appear when using batting_stats

### ISSUE THREAD

**Issue by rshah742** [jldbc/pybaseball#244]
I am using pybaseball 2.2.1, but for some reason when I try and using batting_stats, I don't get data for every MLB player. For example, if I filter for just NYY players, I only get four of them. 

Is anyone else experiencing this? 

![pybaseball](https://user-images.githubusercontent.com/45208747/147857673-abd29d07-6aa3-4400-831b-200aec5d4561.PNG)

**Comment by blacktj** [comment]
If you read through the underlying code, you'll see that qual='y'. Meaning you're only seeing qualifying hitters. By setting qual='n' it returns 1.5k hitters:
<img width="353" alt="Screen Shot 2022-01-01 at 1 41 47 PM" src="https://user-images.githubusercontent.com/9456605/147857837-1a1f1d1a-34af-457c-9724-a878f6f53a6f.png">

**Comment by rshah742** [comment]
> If you read through the underlying code, you'll see that qual='y' as a default. Meaning you're only seeing qualifying hitters. By setting qual='n' it returns 1.5k hitters: <img alt="Screen Shot 2022-01-01 at 1 41 47 PM" width="353" src="https://user-images.githubusercontent.com/9456605/147857837-1a1f1d1a-34af-457c-9724-a878f6f53a6f.png">

Thank you so much!
