### ISSUE TITLE
Drop index in statcast postprocessing

### ISSUE THREAD

**Issue by gwaygenomics** [jldbc/pybaseball#25]
Hi @jldbc - thanks for putting this project together. I am using the `statcast` function to retrieve pitching data, and am proposing a simple change.

Adding `drop=True` in the `reset_index()` call on [line 170 of `statcast.py`](https://github.com/jldbc/pybaseball/blob/master/pybaseball/statcast.py#L170) prevents an unnecessary column named "index". Happy to add change in a future PR.

Thanks again!

**Comment by TheCleric** [comment]
PR created to resolve issue and similar ones.
