### ISSUE TITLE
Several methods in the Lahman package were not working

### ISSUE THREAD

**Issue by cj0121** [jldbc/pybaseball#253]

**Comment by tjburch** [comment]
Could you list which ones and what error messages you were encountering?

**Comment by cj0121** [comment]
I'm not sure if it's a problem on my end, but the awards_managers(),
awards_players(), awards_share_managers(),
awards_share_managers(), college_playing(), hall_of_fame(), salaries(), and
schools() functions all return an similar error message as shown in the
attachment.

Also a minor suggestion: it will be tremendously helpful if all player and
team data come with MLBAM id, fangraph id, or any unique identifier. It
will make joining data with other data sources so much easier. Just a
thought. Thanks!

Tyler Burch ***@***.***> 于2022年4月23日周六 15:52写道：

**Comment by tjburch** [comment]
So I don't see an attachment (guessing you commented via email and not on GitHub directly?).

I'm assuming you're running into a FileNotFoundError. The associated files to the methods you're referencing are now in `.pybaseball/cache/baseballdatabank-master/contrib/`, but as of last release it's looking at `.pybaseball/cache/baseballdatabank-master/core/`. 

However, it looks like this has been resolved with #251 : https://github.com/jldbc/pybaseball/commit/42ad7446e094e9f6818daae4b26e6ea8c309e695. So it should be resolved in the next release.

For now, you can just copy all the stuff in your `/contrib/` to your `/core/` directory and it should work.

**Comment by cj0121** [comment]
Yes that’s the error. Thanks for the clarification.
