### ISSUE TITLE
playerid_reverse_lookup() does not include rookies

### ISSUE THREAD

**Issue by AndrewTrapp24** [jldbc/pybaseball#261]
Newly promoted players do not return names in the playerid_reverse_lookup() function. So far I have noticed issues with Bobby Witt Jr, Steven Kwan and Seiya Suzuki, but I am assuming this issue applies to all new players.

**Comment by dgrochmal** [comment]
From what I can tell in my usage (just player Ids for the sites), it's the FanGraphs ID that's missing for these players:
CJ Abrams 25768
Jose Azocar 18821
Tanner Banks 16990
Felix Bautista 20666
Ronel Blanco 19407
Matt Brash 25756
Diego Castillo 19906
Alexis Diaz 21132
Daniel Duarte 17480
Jhoan Duran 21029
Bryce Elder 27779
Lucius Fox 18899
MacKenzie Gore 22201
Hunter Greene 22182
Jose Herrera 17040
Cooper Hummel 19458
Zach Jackson 19493
Gosuke Katoh 15697
Steven Kwan 24610
Bryan Lavastida 24765
Jake Lemoine 19785
Nick Lodolo 26378
Ron Marinaccio 23488
Yunior Marte 14416
Simon Muzziotti 19553
Adam Oller 20132
Andre Pallante 26108
Jeremy Pena 21636
Joe Perez 22254
Konnor Pilkington 21453
Nick Plummer 18690
Heliot Ramos 22515
Ethan Roberts 24930
Elvin Rodriguez 20962
Julio Rodriguez 23697
Tommy Romero 23465
Phoenix Sanders 20541
JP Sears 23429
Anderson Severino 20582
Collin Snider 23307
Bennett Sousa 21345
Bryson Stott 26294
Robert Suarez 30115
Seiya Suzuki 30116
Spencer Torkelson 27465
Steven Wilson 20353
Josh Winder 24606
Bobby Witt 25764

**Comment by dgrochmal** [comment]
Additional missing rookies:

Angel De Jesus 22323
Yerry De Los Santos 21420
Jason Alexander 19666
Cam Alldred 25078
Nick Allen 22277
Mark Appel 14823
Jonathan Aranda 21837
Gabriel Arias 22563
Graham Ashcraft 27552
Rylan Bannon 19768
Luke Barker 19609
Matt Batten 20157
Brayan Bello 23920
Jake Bird 21267
Dairon Blanco 19779
JJ Bleday 26368
Sean Bouchard 21270
Kyle Bradish 24586
Jonah Bride 24703
Beau Brieske 26079
Alex Call 19296
Yennier Cano 25911
Connor Capel 19983
Vinny Capra 25040
Maximo Castillo 21956
Kody Clemens 20572
Mark Contreras 20122
Narciso Crook 17473
Jose Cuas 17701
Jason Delay 19806
Brendan Donovan 24679
Jeter Downs 22202
Joe Dunand 19727
Ezequiel Duran 23733
Nick Duron 21092
Nathan Eaton 25055
Jerar Encarnacion 21871
Anderson Espinoza 18593
Alex Faedo 19874
Calvin Faucher 20116
Freddy Fermin 21840
Bowden Francis 20548
Matt Gage 17381
Dermis Garcia 20926
Maikel Garcia 22715
Logan Gillaspie 22461
Oscar Gonzalez 20970
Nolan Gorman 22263
Riley Greene 25976
Michael Grove 23221
Darick Hall 19717
Caleb Hamilton 19842
Michael Harris 25931
Elier Hernandez 13750
Ivan Herrara 20599
Brewer Hicklen 20450
Garrett Hill 25097
Sean Hjelle 21481
Colin Holderman 22361
Tyler Holten 26231
Brandon Hughes 23460
Nolan Jones 20529
Michael Kelly 12791
Buddy Kennedy 22505
Ray Kerr 23809
Caleb Kilian 26213
George Kirby 25436
Jared Koenig 27517
Mark Kolozvary 21304
Jason Krizan 12394
Evan Lee 24988
Korey Lee 25543
Royce Lewis 20437
Matthew Liberatore 22294
Zach Logue 20231
Christian Lopes 13472
David MacKinnon 19625
Bligh Madris 20054
Davis Martin 21448
Adrian Martinez 21023
Michael Massey 27684
J.J. Matijevic 20165
Kirk McCarty 20555
Mickey McDonald 20533
MJ Melendez 22197
Max Meyer 27474
Jose Miranda 20538
Cal Mitchell 22169
Elehuris Montero 20543
Francisco Morales 22913
Christopher Morel 21897
Gabriel Moreno 22664
Penn Murfee 25174
Parker Mushinski 21324
James Naile 18186
Cristofer Ogando 20667
Chris Okey 19245
Jermaine Palacios 18371
Richie Palacios 24589
Michael Papierski 21386
Vinny Pasquantino 27676
Liover Peguero 24273
Ryan Pepiot 26221
Rene Pinto 19859
Nick Pratto 22117
Denyi Reyes 20526
Kramer Robertson 20022
Kenny Rosenberg 20009
Bubby Rossman 17179
Esteury Ruiz 21780
Adley Rutschman 26288
Cole Sands 21461
Cody Sedlock 19357
Brian Serven 19422
Chase Silseth 30074
Ethan Small 26364
Chad Smith 20190
Josh H. Smith 26396
Canaan Smith-Njigba 23264
Jared Solomon 23425
Lenyn Sosa 22896
Michael Stefanic 25353
Kyle Stowers 26151
Peter Strzelecki 21367
Beau Sulser 23420
Jack Suwinski 22244
Travis Swaggerty 24491
Matt Swarmer 19705
Jackson Tetreault 20565
Alek Thomas 23792
Zack Thompson 25918
Tanner Tully 19518
Erich Uelmen 20323
Nick Vespi 21093
Cam Vieaux 19529
David Villar 24782
Steele Walker 22093
Jake Walsh 20227
Joey Wentz 19962
Marcus Wilson 17910
Josh Winckowski 22387
William Woods 25075
Juan Yepez 18400
Danny Young 18439
Aneurys Zabala 20802

**Comment by dgrochmal** [comment]
This appears to be fixed, based on my manual testing

**Comment by tjburch** [comment]
Agreed, very much appreciate the follow up, sorry there wasn't a resolution earlier.
