### ISSUE TITLE
When do stats update?

### ISSUE THREAD

**Issue by 2Skupz** [jldbc/pybaseball#268]
Midnight? 3am ET? 9am ET?

**Comment by tjburch** [comment]
Depends on the method. Pybaseball is just scraping other data sources, so it's dependent on when the underlying source is updated. Statcast methods are from Baseball Savant, [which updates at 3 am EST](https://baseballsavant.mlb.com/about#:~:text=It%20updates%20daily%20at%203,functionality%20will%20be%20added%20often.). Other methods may be different.

**Comment by 2Skupz** [comment]
Of course, these are scraping in real time. Thank you!
