### ISSUE TITLE
lxml update

### ISSUE THREAD

**Issue by asmohov** [jldbc/pybaseball#276]
![image](https://user-images.githubusercontent.com/33326755/174531648-8df8af61-6800-4b62-b856-cb7c1f6af481.png)

current version of lxml doesn't work with the version of pybaseball; raises an import error

trying to install older version of lxml also doesn't work (fails trying to install)

**Comment by tjburch** [comment]
I can't reproduce this one. Does it still seem to be a problem? If so, can you give me versions to reproduce?
