### ISSUE TITLE
Channel for support discussion

### ISSUE THREAD

**Issue by PoliTwit1984** [jldbc/pybaseball#277]
Any chance we could create an official or unofficial discord server or slack channel for users that want to help other users?

**Comment by schorrm** [comment]
We already have a slack chat, we could do that there or on Discord I guess. Is there a preference for Slack or Discord here?

**Comment by PoliTwit1984** [comment]
No preference at all. Would just love a place to collaborate.

**Comment by meirelon** [comment]
👆

**Comment by tjburch** [comment]
Personally I'm against private/invite chats related to usage and support of a library of this sort (developers chat is a different animal imo). Too easy to get stale and for people to feel out of the loop. Something open and accessible to the public is a better method so the same answers don't get revisited over and over. The [pymc discourse](https://discourse.pymc.io/) does a really good job of this for their package, maybe that is something that we could look into.

**Comment by schorrm** [comment]
I don't want yet another thingy, I think we are better off making a publicly accessible Discord or opening the gates to the Slack

**Comment by tjburch** [comment]
Discord added in #297.
