### ISSUE TITLE
Typo in first_name column name for statcast_batter_exitvelo_barrels

### ISSUE THREAD

**Issue by miltiades-the-general** [jldbc/pybaseball#279]
The column titles for the statcast_batter_exitvelo_barrels has a space before the first_name index. It took me a while to realize what was happening when I was trying to reorganize my data. 
![image](https://user-images.githubusercontent.com/97767157/180105408-204284dd-f0f4-4681-8d48-bc10f7020cac.png)

**Comment by BrayanMnz** [comment]
Since this was addressed on https://github.com/jldbc/pybaseball/pull/280/
and merged I think you could close this one also. 

cc: @tjburch @schorrm

**Comment by tjburch** [comment]
Until PyPi picks up 2.2.3 rather than 2.2.1 I'm erring on the side of caution closing issues which are still present in 2.2.1, so people can more easily reference problems they may run into.

**Comment by tjburch** [comment]
Resolved and in pypi following closing of #281.
