### ISSUE TITLE
List of game_ids

### ISSUE THREAD

**Issue by kjordan18** [jldbc/pybaseball#28]
Hey @jldbc thanks for creating this module! I'm currently using the statcast_single_game module for a project, and was wondering if you had a list of game_ids for previous seasons, or if you could point me in the right direction I would really appreciate it!

**Comment by jldbc** [comment]
Hi @kjordan18, I'll look into this. I think I have the full file somewhere.

**Comment by jldbc** [comment]
Give this a try. It should be everything from 2008 - 2017. 
[gameids.txt](https://github.com/jldbc/pybaseball/files/2276347/gameids.txt)
