### ISSUE TITLE
Statcast Queries Currently Broken

### ISSUE THREAD

**Issue by jldbc** [jldbc/pybaseball#30]
Baseball Savant changed some column names, which is currently breaking the `statcast` function. Bill Petti gives some details [here](https://twitter.com/BillPetti/status/1043938694762237952).

I'll look into the mapping later and try to get a quick deploy out.

**Comment by jldbc** [comment]
#e3dcb01037f62663f3702d6be5c6285f56ffc64c should fix this. An update has been deployed to PyPI so this should be fixed by either rebuilding from the repo or upgrading via pip.

**Comment by jldbc** [comment]
@kjordan18 have you updated? I deployed a fix that was working for me

**Comment by kjordan18** [comment]
@jldbc yes it's working now, sorry for the trouble. Thanks for your help!
