### ISSUE TITLE
Statcast Fielding Percentile Rank

### ISSUE THREAD

**Issue by hexagonsun24** [jldbc/pybaseball#302]
Maybe I'm missing something, but is there a function that allows for Statcast fielding percentile_ranks?

**Comment by tjburch** [comment]
It's not clear to me what you're looking for. Is this something on Savant? 

If you just want to know where percentiles lie for a given metric:

```
>>> data = statcast_outs_above_average(2019, "all", 50)
>>> np.percentile(data.outs_above_average, np.arange(10, 100, 10))  # deciles
array([-7. , -5. , -3. , -1. ,  0. ,  1. ,  2.6,  4. ,  7.2])
```

**Comment by BrayanMnz** [comment]
This can be closed. @tjburch 
No more inputs from @hexagonsun24
