### ISSUE TITLE
Fangraphs Data is Incomplete

### ISSUE THREAD

**Issue by TobiasCortese** [jldbc/pybaseball#306]
The functions pybaseball.pitching_stats( 2019, 2019 )  and pybaseball.datasources.fangraphs.fg_pitching_data(2019) only bring in 61 rows and obviously there were more than 61 pitchers in 2019. is this expected? if so, why? if not, is there a fix on the way?

**Comment by tjburch** [comment]
It's only pulling in qualified pitchers. You need to disable the qual argument. See: docs/pitching_stats.md

**Comment by TobiasCortese** [comment]
thanks @tjburch!
