### ISSUE TITLE
playerid_lookup throws and error

### ISSUE THREAD

**Issue by jlmayfield** [jldbc/pybaseball#326]
When running the example from the documentation I get the following error:

```python
ValueError: Usecols do not match columns, columns expected but not found: 
['mlb_played_first', 'mlb_played_last', 'name_last', 'key_mlbam', 'key_retro', 
'key_fangraphs', 'key_bbref', 'name_first']
```

This was on a setup with a freshly installed pybaseball, both from pip and from github today, 2/23/2023.

**Comment by tjburch** [comment]
this shouldn't happen after #308 and #309. They're not in pypi yet so it won't be in via pip but should work from a github install.

@schorrm can we version bump so this gets resolved?

**Comment by schorrm** [comment]
@tjburch of course

**Comment by tjburch** [comment]
@jlmayfield, try from pip now.

**Comment by tjburch** [comment]
Closing Friday 3/3 unless more problems arise

**Comment by jlmayfield** [comment]
@tjburch reinstalled from pip and the problem is gone. Thanks!
