### ISSUE TITLE
schedule and record errors

### ISSUE THREAD

**Issue by 2Skupz** [jldbc/pybaseball#331]
Following the example word for word in the documentation, I get the following

>>> from pybaseball import schedule_and_record
>>> data=schedule_and_record(1927,'NYY')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kensmacmini/Library/Python/3.9/lib/python/site-packages/pybaseball/cache/cache.py", line 58, in _cached
    result = func(*args, **kwargs)
  File "/Users/kensmacmini/Library/Python/3.9/lib/python/site-packages/pybaseball/team_results.py", line 119, in schedule_and_record
    table = get_table(soup, team)
  File "/Users/kensmacmini/Library/Python/3.9/lib/python/site-packages/pybaseball/team_results.py", line 28, in get_table
    raise ValueError("Data cannot be retrieved for this team/year combo. Please verify that your team abbreviation is accurate and that the team existed during the season you are searching for.")
ValueError: Data cannot be retrieved for this team/year combo. Please verify that your team abbreviation is accurate and that the team existed during the season you are searching for.

**Comment by tjburch** [comment]
It works for me:

```
>>> from pybaseball import schedule_and_record
>>> data=schedule_and_record(1927,'NYY')
http://www.baseball-reference.com/teams/NYY/1927-schedule-scores.shtml
>>> data
                  Date   Tm Home_Away  Opp W/L     R  ...  Time  D/N Attendance   cLI Streak Orig. Scheduled
1      Tuesday, Apr 12  NYY      Home  PHA   W   8.0  ...  2:05    D    72000.0  2.55      1            None
2    Wednesday, Apr 13  NYY      Home  PHA   W  10.0  ...  2:15    D     8000.0  2.71      2            None
3     Thursday, Apr 14  NYY      Home  PHA   T   9.0  ...  2:50    D     9000.0  2.84      2            None
4       Friday, Apr 15  NYY      Home  PHA   W   6.0  ...  2:27    D    16000.0  2.86      3            None
5     Saturday, Apr 16  NYY      Home  BOS   W   5.0  ...  2:05    D    25000.0  3.00      4            None
..                 ...  ...       ...  ...  ..   ...  ...   ...  ...        ...   ...    ...             ...
151     Sunday, Sep 25  NYY      Home  DET   L   1.0  ...  2:20    D    25000.0   .00     -1            None
152    Tuesday, Sep 27  NYY      Home  PHA   W   7.0  ...  2:12    D    15000.0   .00      1            None
153   Thursday, Sep 29  NYY      Home  WSH   W  15.0  ...  1:58    D     7500.0   .00      2            None
154     Friday, Sep 30  NYY      Home  WSH   W   4.0  ...  1:38    D     8000.0   .00      3            None
155    Saturday, Oct 1  NYY      Home  WSH   W   4.0  ...  1:35    D    20000.0   .00      4            None

[155 rows x 20 columns]
```

Couple of thoughts. One, the first part of the error message indicates some error with a cached result. Maybe try either:

```
from pybaseball import cache
cache.disable()
```

or 

```
from pybaseball import cache
cache.purge()
```

The other thought is that `During handling of the above exception, another exception occurred:` indicates that another error was thrown - do you happen to have that? Perhaps that error blocked bbref from being scraped correctly.

**Comment by 2Skupz** [comment]
Update. I'd run the code too often. BRef blocked me.
