### ISSUE TITLE
schedule_and_record keeps throwing an error

### ISSUE THREAD

**Issue by teagenwilliams** [jldbc/pybaseball#339]
I was using to schedule_and_record() to retrieve individual game data for the 2022 season. It was working without any issues then all of a sudden start throwing:
 "ValueError: Data cannot be retrieved for this team/year combo. Please verify that your team abbreviation is accurate and that the team existed during the season you are searching for."

I am not sure what the problem is since the arguments I am inputing have not changed. Any help to fix this would be appreciated.

**Comment by tjburch** [comment]
Can you post the call that throws the error (e.g. what team/date combo?)

**Comment by teagenwilliams** [comment]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/92009858/224846069-0369f3de-53d7-4bf6-87bd-157ac17084f6.png">

**Comment by teagenwilliams** [comment]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/92009858/224846169-fdab9c0b-1dfa-40c3-9c72-944479c6d4d9.png">
Even the example in the write up is throwing the error

**Comment by tjburch** [comment]
It looks like it's not retrieving the table at all. Did you run this in a loop? I can test later but I would bet that you hit the request limit.

**Comment by teagenwilliams** [comment]
That's probably my issue. Thanks!

**Comment by tjburch** [comment]
You can add sleeps to prevent. The most recent version introduced a session manager to try to prevent this from happening. Have you updated to 2.2.5 yet?

**Comment by teagenwilliams** [comment]
I'm not sure if I was before, but I am now

**Comment by teagenwilliams** [comment]
Adding the sleeps fixed the issue. Thanks again

**Comment by tjburch** [comment]
Did it persist in 2.5.5 before the sleeps? Glad you got it sorted out.
