### ISSUE TITLE
Missing savant data for the NYM game 

### ISSUE THREAD

**Issue by michellebrandao7** [jldbc/pybaseball#361]
Hi, I can't find savant data for the game NYM vs WSH at  2023-05-14 at 11:35am using the function  statcast(start_dt="2023-05-14", end_dt="2023-05-14"). it was a double header but only see one NYM game for that day. Is anyone having the same issue?

**Comment by blacktj** [comment]
That was a continuation of the 2023-05-13 game was it not?

**Comment by michellebrandao7** [comment]
It was indeed. I can that game on 2023-05-13. Thanks!!
