### ISSUE TITLE
Player names in Baseball Reference stats contain mis-encoded non-ASCII characters

### ISSUE THREAD

**Issue by AndrewsOR** [jldbc/pybaseball#393]
The FanGraphs functions `pitching_stats()` and `batting_stats()` appear to convert names from that [site](https://www.fangraphs.com/leaders/major-league?pos=all&stats=bat&lg=all&qual=y&type=8&season=2023&month=0&season1=2023&ind=0) such as Ronald Acuña Jr. and José Abreu to `Ronald Acuna Jr.`, `Jose Abreu` etc., which are recognizable if not entirely correct.

On the other hand, the Baseball Reference functions `batting_stats_bref()` and `pitching_stats_bref()` return what seems like mis-converted HTML encodings of those names, resulting in lower readability, although the names on the [site](https://www.baseball-reference.com/players/a/acunaro01.shtml) itself appear correct.

For example:

```
import pybaseball as pb
df_bref_batting = pb.batting_stats_bref(2023).sort_values("mlbID")
df_bref_pitching = pb.pitching_stats_bref(2023).sort_values("mlbID")

for side, df in zip(["batting","pitching"],[df_bref_batting,df_bref_pitching]):
    print(side)
    print(df[df["Name"].str.contains("x")][["Name","mlbID"]].head().to_string(index=False)+"\n")
```
prints:

```
batting
                        Name  mlbID
           Manny Pi\xc3\xb1a 444489
     Mart\xc3\xadn Maldonado 455117
           Sandy Le\xc3\xb3n 506702
Avisa\xc3\xadl Garc\xc3\xada 541645
         Carlos P\xc3\xa9rez 542208

pitching
                   Name  mlbID
           Max Scherzer 453286
Mart\xc3\xadn Maldonado 455117
     Luis Garc\xc3\xada 472610
   Jos\xc3\xa9 Quintana 500779
              Alex Cobb 502171
```

My current workaround is to use `playerid_reverse_lookup` to bridge to FanGraphs names and use those instead. (I like to use the Baseball Reference batting stats because of how it labels players who played in multiple teams/leagues in a given season, providing both team names instead of "---".)

I love `pybaseball`... thank you!

**Comment by BrayanMnz** [comment]
Hi, these are "tildes" for spanish words, 
I have a workaround for this in an internal project that maybe can be useful. 

Will try to replicate your example and apply my workaround

**Comment by BrayanMnz** [comment]
The issue is because we are wrongly encoding a _**bytes**_ object parsed to _**string**_ 
what we need to do instead is, decode the _**bytes**_ object directly. 

I'll submit a PR to fix this.

**Comment by BrayanMnz** [comment]
Hi, @AndrewsOR this now has been merged into master
just need to wait for the next pybaseball release.

**Comment by BrayanMnz** [comment]
This issue can be closed since the solution was merged. @schorrm

**Comment by AndrewsOR** [comment]
Thank you @BrayanMnz !
