### ISSUE TITLE
Need reverse playerid_lookup() function

### ISSUE THREAD

**Issue by jldbc** [jldbc/pybaseball#4]
The current playerid_lookup() function finds player ids, taking name as input. Something doing the opposite would be useful, taking an id from a statcast query as input and returning the player's name. The option to do this in bulk would be even better.

**Comment by jelloslinger** [comment]
Sent you a pull request.  Check it out and let me know if this was along the lines of what you were looking for.

**Comment by jldbc** [comment]
Looks good! Just merged #7. As a follow-up to this I'll add it to __init__.py and create some docs unless you beat me to it.
