### ISSUE TITLE
PyBaseball module not found in JupyterLab notebook

### ISSUE THREAD

**Issue by gianp21** [jldbc/pybaseball#401]
I'm trying to execute 'from pybaseball import statcast' on a JupyterLab notebook like normal, but now I'm receiving an error code stating the module doesn't exist. Does anyone know what's going on with this or how to fix it? Thanks!

**Comment by BatDad7** [comment]
I second this

**Comment by kevingarnett** [comment]
> I'm trying to execute 'from pybaseball import statcast' on a JupyterLab notebook like normal, but now I'm receiving an error code stating the module doesn't exist. Does anyone know what's going on with this or how to fix it? Thanks!

Are you using any tools such as virtualenv or pipenv?

**Comment by gianp21** [comment]
No, I'm not using either of those, but I think I ended up discovering the issue. It has to do with the web version of JupyterLab not having the necessary updates. I installed JupyterLab on my desktop and verified I had the most recent version of Python and it worked without issue now. Thanks for the help though!

**Comment by kevingarnett** [comment]
Perfect. Thanks for the update!
