### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by msoud25** [jldbc/pybaseball#429]
When opening this repo in VS Code, I keep getting module and package errors on imports. I don't know if it's just on my end, I'm fairly new to python, but I wanted to know if there's something I'm not seeing.

For example, an import on statcast.py:
`import pybaseball.datasources.statcast as statcast_ds`
but that threw an error and I fixed it to this:
`from .datasources import statcast as statcast_ds`

similarly on retrosheet.py:
`from pybaseball.utils import get_text_file`
was fixed to:
`from .utils import get_text_file`

**Comment by bdilday** [comment]
This sounds like an issue on your end. Can you give some more details? Are you on windows? which directory are you in when you open vscode? did you install pybaseball locally with pip? did you set a interpreter for your vscode session?

**Comment by msoud25** [comment]
I found the issue, I was using an anaconda environment which caused it to throw errors. I cloned the repo through git, and I'm using windows, is there a way to import it in a jupyter notebook? I tried importing sys and adding it to path but it didn't work.

**Comment by bdilday** [comment]
I'm not the best person to help out here, windows, anaconda, and jupyter notebooks are all things I don't use! If I was doing it on linux or macos I would create a virtual env using `python -m venv`, start up that environment, git clone the pybaseball repo and install it with `python3 -m pip install .`  and also jupyter `python3 -m pip install jupyter`, then `jupyter notebook`. I don;t know what the equvilant would be in windows, but maybe someone with experience can chime in ?

**Comment by bdilday** [comment]
one thing that might be helpful, after you open a notebook you can do 
```
%pip install pybaseball
```

and it will install pybaseball from pypi into you notebook environment

**Comment by msoud25** [comment]
that worked, thanks for the tip!
