### ISSUE TITLE
Does a session need to be closed (or a cache cleared) for bref team stats?

### ISSUE THREAD

**Issue by ChapelHeel66** [jldbc/pybaseball#444]
If I  run team_batting_bref (or team_pitching_bref) on consecutive days, the team stats do not update to current.  

Suppose I do this on Day 1:  battingdf = team_batting_bref('OAK',2024).  I get the message "Getting Batting Data: 2024 OAK" and it pulls the team stats as of Day 1, as expected.

Now on Day 2, I run the same (after the stats have been updated on bbref).  On Day 2, I do NOT get the message  "Getting Batting Data: 2024 OAK", and when the script finishes (without errors), the stats are the same as OAK's stats on Day 1.  (Yes they played a game, haha).  It's like the team_batting script thinks it does not need to fetch new data because it already has it somewhere.

It makes me wonder if the session used to pull the stats on Day 1 is cached somewhere and needs to be cleared at the end of the script.

All suggestions for solutions are appreciated.

**Comment by bdilday** [comment]
can you try the following and see if it works as expected?

```
from pybaseball import cache
cache.disable()

battingdf = team_batting_bref('OAK',2024)
```

**Comment by ChapelHeel66** [comment]
Yes, that did it.  Thanks so much!!!
