### ISSUE TITLE
Question - Statcast batter

### ISSUE THREAD

**Issue by cmartinez01** [jldbc/pybaseball#51]
quick question - is there an easy way to distinguish every at-bat (like an at bat id) when using the statcast batter package?

**Comment by TAThor** [comment]
The first thing that I could think of is to get the index for each non-NaN event in the 'events' column, and then an 'at bat' would be the non-NaN event's index and all indexes leading to the next non-NaN event. 

The 'events' column is NaN for everything except for the final outcome of the at bat (i.e. home_run, strikeout, single, etc.).

**Comment by djcunningham0** [comment]
There's an 'at_bat_number' column with unique values for each at-bat in each game. You can combine game_pk, home_team, away_team, and at_bat_number to get a unique at-bat identifier.
