### ISSUE TITLE
Question- filter by minimum number of pitches

### ISSUE THREAD

**Issue by genericzer0** [jldbc/pybaseball#53]
Is it possible to filter by a minimum number of pitches/events? For example I want to get every fastball for a certain time period thrown by pitchers who threw at least "x" amount of fastballs in that time period.

**Comment by reddigari** [comment]
That sounds like it'd be tricky to implement on the query side, but is a pretty quick data wrangling task if you've already scraped the full data:

```Python
data = pybaseball.statcast(...)
data.dropna(subset=["pitch_type"], inplace=True)  # drop rows without pitch type
fb = data.loc[data.pitch_type.str.startswith("F")]  # subset to fastballs
fb_counts = fb.groupby("pitcher").size()  # group by pitcher; count rows
p_ids = fb_counts.loc[fb_counts >= x].index  # ids of pitchers with >= x fastballs
new_data = fb.loc[fb.pitcher.isin(p_ids)]  # subset to those pitchers
```
