### ISSUE TITLE
Stat types for statcast are named differently from the baseball savant CSV documentation.

### ISSUE THREAD

**Issue by kiikoh** [jldbc/pybaseball#55]
https://baseballsavant.mlb.com/csv-docs

Some items don't match like hit distance is hit_distance_sc which is just hit_distance in the docs.

Launch angle is launch_speed_angle, I don't see the point of this, and if there is one, a full documentation needs to be made. 

Also, quick help, can someone show me where I can find if the strike was called or swung on.

**Comment by schorrm** [comment]
I think this is just the backend being weird, not on us
