### ISSUE TITLE
download_lahman() pull OLD Lahman dataset (baseballdatabank-2017.1)

### ISSUE THREAD

**Issue by prs-watch** [jldbc/pybaseball#57]
When I execute `pybaseball.download_lahman()`, following is happened.

![image](https://user-images.githubusercontent.com/28729575/59290874-8ed77e80-8cb4-11e9-9f96-121650f88a0f.png)

This problem was already fixed by [this commit](https://github.com/jldbc/pybaseball/commit/86dab849b4e2d5b7c06173b21306d419e7c825e1#diff-3c3be59b9db4b8da164eaa15c5642ca0). But I guess this fix maybe not on released module to `PyPI`.   
(I checked `1.0.5` and `1.0.7`, but both set `baseballdatabank-2017.1.zip` to `lahman.url`).

![image](https://user-images.githubusercontent.com/28729575/59291363-a400dd00-8cb5-11e9-8746-8401845ae35b.png)

Could you check how released module is right now, and fix this problem?

**Comment by schorrm** [comment]
PyPI is just behind. If you clone the repo and install it won't be an issue

**Comment by prs-watch** [comment]
> If you clone the repo and install it won't be an issue

Yeah I already solved this problem by that way a few days ago. `master` branch worked well.  

> PyPI is just behind.

Why does this happen? Is `PyPI` module not synchronized `master` branch's version?

**Comment by schorrm** [comment]
PyPI will be synced to the releases soon after the CI is ready
