### ISSUE TITLE
Set correct data types in Statcast data

### ISSUE THREAD

**Issue by djcunningham0** [jldbc/pybaseball#59]
Currently all numeric columns in the Statcast data are coerced to a float data type. This happens in the `postprocessing` function in `statcast.py`.

```
numeric_cols = ['release_speed','release_pos_x','release_pos_z','batter','pitcher','zone','hit_location','balls',
                'strikes','game_year','pfx_x','pfx_z','plate_x','plate_z','on_3b','on_2b','on_1b','outs_when_up','inning',
                'hc_x','hc_y','fielder_2','vx0','vy0','vz0','ax','ay','az','sz_top','sz_bot',
                'hit_distance_sc','launch_speed','launch_angle','effective_speed','release_spin_rate','release_extension',
                'game_pk','pitcher.1','fielder_2.1','fielder_3','fielder_4','fielder_5',
                'fielder_6','fielder_7','fielder_8','fielder_9','release_pos_y',
                'estimated_ba_using_speedangle','estimated_woba_using_speedangle','woba_value','woba_denom','babip_value',
                'iso_value','launch_speed_angle','at_bat_number','pitch_number','home_score','away_score','bat_score',
                'fld_score','post_away_score','post_home_score','post_bat_score','post_fld_score']

data[numeric_cols] = data[numeric_cols].astype(float)
```

Many of those numeric columns always contain integer values (balls, strikes, outs_when_up, etc.). These columns should be coerced to an int data type.

Perhaps more importantly, many of the other columns are ID values (batter, pitcher, game_pk, etc.). It would make more sense to coerce these columns to a string data type (or int would also be better than float). 

I would recommend the following changes in the `postprocessing` function:
* Remove 'batter', 'pitcher', and all other ID columns from the numeric_cols list.
* Create a new int_cols list with 'balls', 'strikes', and all other columns that always contain integer values. Then coerce these columns to an int data type.
    + **Edit:** The int data type doesn't allow for nulls. If you're willing to make Pandas >= 0.24.0 a requirement, then you could use the Pandas [nullable integer](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html) data type. (This data type could also be useful in some other places)

**Comment by schorrm** [comment]
@TAThor , @andersonfrailey -- what do you guys think about requiring this?
Quoting from the NumPy docs: "Changed in version 1.0.0: Now uses pandas.NA as the missing value rather than numpy.nan."
So I think we'd probably want to mandate version 1+?

**Comment by andersonfrailey** [comment]
I think mandating 1+ is fine. Especially since we're effectively moving to python 3.5+ only support by using f-strings (which I also fully support btw).

**Comment by schorrm** [comment]
3.6, but yeah. I think we can do this, and we can do the nullable int (="Int64").
I don't know about pandas.NA vs np.nan, but it just strikes me as simpler to mandate 1+ and not worry about this.
This is a nice-to-have, not necessarily top priority at the moment to go and implement, but if anyone wants to do this, I'd be delighted.

**Comment by TheCleric** [comment]
This should now be resolved in #106

**Comment by TheCleric** [comment]
@djcunningham0 can you confirm if this is resolved now?

**Comment by djcunningham0** [comment]
Looks good! Thanks for working on this, everyone!
