### ISSUE TITLE
Create dataset offline Vs Request to website

### ISSUE THREAD

**Issue by Marlysson** [jldbc/pybaseball#6]
Why don't you create a dataset from this data?
Instead of run every time a request to a website hosted in internet..

Make sense this idea.....

**Comment by jldbc** [comment]
I don't own any special rights to the data, so I'm not sure about publishing a complete dataset online. Creating a copy for your own use makes sense though if you plan on returning to the data often.

Also, there are new games every day during the season, so it's nice to at least have the option to pull updated data whenever you need it.

**Comment by Marlysson** [comment]
Great..good arguments
