### ISSUE TITLE
Broken scraper

### ISSUE THREAD

**Issue by jamiek5** [jldbc/pybaseball#61]
The scraper broke a couple days ago. I fixed it and submitted a PR (https://github.com/jldbc/pybaseball/pull/60).

**Comment by jldbc** [comment]
Merged! I'll update this issue when it's updated on pypi.

**Comment by jldbc** [comment]
A new version is up (1.0.8). Can you confirm that it's working for you?

**Comment by jamiek5** [comment]
Works for me, thanks
