### ISSUE TITLE
Maintaining this package

### ISSUE THREAD

**Issue by schorrm** [jldbc/pybaseball#67]
It's been a really long time since any pull requests have gotten dealt with. Would it be possible to get some more maintainers here? I'm extremely thankful for what you've done, and of course, I understand you have a real job and stuff, but I don't. I'm a 4th year CompSci student with some time to kill and I'd love to help out as a maintainer, and I'm sure there are other contributors here who would also be happy to help maintain this package.
Thank you

**Comment by jlutz777** [comment]
I'm curious if there is any movement on this. I ask because I'd like to start contributing, but I'm a little concerned that this work would be for naught. It seems like PRs and issues are not moving any longer.

**Comment by schorrm** [comment]
If we could agree on a fork too, that might be an option. I'd be happy to help run it too, I've got enough time to review merge requests and stuff.

**Comment by double-dose-larry** [comment]
Love to see an active maintainer on this repo

**Comment by schorrm** [comment]
I'm happy to do that, I would just want to know that there'd be sign-on -- that people would bring their pull requests and modifications over if we fork it.

**Comment by JosephAlanLane** [comment]
I'm actively using this project for Sabermetrics Research at my University, and am very thankful for it!

**Comment by michaelbushe** [comment]
Does anyone have a fork with any of the PR's her merged?

**Comment by schorrm** [comment]
Yeah, the new stuff is on my fork

**Comment by TAThor** [comment]
I say we move to @schorrm's fork, and consider that the new official pybaseball repo since this one is no longer being maintained. I've only contributed a small amount to this project, but I'd love to see it actively managed. Especially with this odd season we're about to have.

I've already deleted this repo (jldbc's) from my forks I now consider @schorrm's my official pybaseball repo, and this is where I will contribute all future work.

I hope you guys join me in this migratory effort.

**Comment by RyanG73** [comment]
Can someone give the 101 on the differences between the original pybaseball and the proposed new master? Aside from maintaining issues are there systematic differences? I'm open to the idea of the new master and helping to maintain, I'm just curious where things stand.

**Comment by schorrm** [comment]
@RyanG73 -- there is no systematic difference right now, it's the same thing but with a whole bunch of new features added. The idea is to take this and keep moving it forward.
Oh, and also, we're allowing f-strings now.

**Comment by schorrm** [comment]
I will be taking it over.

**Comment by schorrm** [comment]
Closing, see #80
