### ISSUE TITLE
Making a fork that will be maintained

### ISSUE THREAD

**Issue by schorrm** [jldbc/pybaseball#68]
Hi guys,
I'm on GitHub Pro, I'm happy to work on this, I have a fork already -- what would you fine folks say to moving to there and working over there?

**Comment by a-fanet** [comment]
Can I join you in this venture, I’ve been looking on a side project to work on

**Comment by schorrm** [comment]
Happy to have whoever on, if there's agreement to coalesce around a fork

**Comment by JosephAlanLane** [comment]
Great, would love to help. Thanks for picking this back up @schorrm!

**Comment by a-fanet** [comment]
Sorry, I'm a bit of a source control noob, not sure what you mean by coalescing around a fork. Can someone explain and how that would be reflected in a pull to my local machine

**Comment by schorrm** [comment]
I mean that people would make pull requests to my fork and I'd merge them and keep stuff updated, and then people could clone from there.

**Comment by schorrm** [comment]
I'm going to try and add some stuff I've been working on for handling Retrosheet stuff and when I've got my WPA calculation stuff ready. I'd be delighted if you guys could submit PRs to my fork so we can get some stuff moving there

**Comment by schorrm** [comment]
I added Tim Andrews' PR for multilookup to there. Tyler Liu is adding batter statcast data. Let's do this!
Maybe later we can do this under a different name and I'll add a PyPI integration so the progress can go back on PyPI?

**Comment by schorrm** [comment]
the fork is now back here
