### ISSUE TITLE
batting_stats_range  and pitching_stats_range - IndexError: list index out of range

### ISSUE THREAD

**Issue by martinpiria** [jldbc/pybaseball#81]
I'm running batting_stats_range and pitching_stats_range once a day for the last 3 months with range parameters of the day I'm currently running.
Been getting data for both every day until July 27th, 2020, after that date I've been getting that error every day. Nothing changed from my side so I assume it's an issue with pybaseball API or one of its providers.

Is anyone else experiencing the same issue?

**Comment by schorrm** [comment]
I think this should be addressed in the fork. I'll migrate the changes from the fork to here, and let me know if it still fails.

**Comment by martinpiria** [comment]
Ok awesome thanks.
When should the migration be live?

**Comment by schorrm** [comment]
hopefully tomorrow, I'll notify in this thread when it is up

**Comment by martinpiria** [comment]
Great, thanks!

**Comment by schorrm** [comment]
Okay, it's updated. Pull the changes, try again, please let me know.

**Comment by martinpiria** [comment]
@schorrm thanks! What would the latest version be?
Currently using:
pybaseball==1.0.7

**Comment by schorrm** [comment]
Try installing from source based on the repo.

**Comment by martinpiria** [comment]
I currently have that version set up in my requirements.txt file which installed in the pipeline and deployed in AWS, what should I change in the requirements.txt file to start using the source based on the repo?

**Comment by schorrm** [comment]
Hmm. Given all of that, maybe just wait for the release. I'm just waiting on James giving me access to the settings so I can set up a CI for PyPI

**Comment by martinpiria** [comment]
@schorrm Let me know the version number when it's ready and I'll try it. Thanks a lot!

**Comment by schorrm** [comment]
@martinpiria it is up now, V. 2

**Comment by martinpiria** [comment]
@schorrm Thanks! I'll try it and let you know

**Comment by martinpiria** [comment]
@schorrm Tested and worked! Thanks a lot!

**Comment by schorrm** [comment]
Great! Thanks

**Comment by martinpiria** [comment]
@schorrm Checked for last week's days and worked fine, but today I ran it for the current date and responded with the same error:
list index out of range
There should be data for today right?

**Comment by schorrm** [comment]
I don't think so?

**Comment by martinpiria** [comment]
@schorrm If there where matches played yesterday, shouldn't be new score data for today?

**Comment by martinpiria** [comment]
@schorrm No new data scraped yesterday at 12 GMT nor today at the same hour. 
Is that expected or could there be an issue with the version?
