### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by TheCleric** [jldbc/pybaseball#85]
I've been using this library for a little bit (and just submitted my first PR!) and have really been enjoying it.

I have a few suggestions that I'd like to make. I'm more than willing to do a lot of the work on these suggestions, but wanted to make sure I would be on the same page with other devs before I just start throwing code over the wall.

1. Add some unit/integration tests. This library would be ripe for adding some unit and integration tests. Both to help make sure code changes are good, but also as a way to determine if an external data source format has changed.

2. Refactor/reuse code. It seems that a lot of the code that is used for the same site (e.g., FanGraphs, BRef) is very repetitive. I think it would be great to distill some of this down to some shared code to help minimize issues when changes are made. Would do this after the above suggestion to ensure that the library is 100% backwards compatible.

3. Adding a caching layer. Sometimes when making calls to FanGraphs, the site will start rejecting your requests for exceeding their rate limit. Locally I wrote a caching wrapper that will save my DataFrames to CSV and return those if available. Integrating this into the library would allow others to take advantage.

4. Add an extra field to the FanGraphs results that returns a column that is joinable to the other data. E.g., team data or player data. Right now the best we'd be able to get is the FanGraphs integer id. We may have to set up our own internal mapping for teams. There are some other sources we could tap into, such as one of these for players:

> http://crunchtimebaseball.com/baseball_map.html
> https://www.smartfantasybaseball.com/tools/

Let me know what you folks think. Not trying to rock the boat, just trying to take this thing to the next level.

**Comment by schorrm** [comment]
Re 4 -- we have mappings for the FG integer ID. You can join through those also if you want.
Re 1: yeah, that's a good idea. It would take time to roll out for all the prior stuff though.
2: Sure. There's a bunch of the stuff that is already good with reuse, there's plenty more that could be more precise.
3: Honestly, I think this is probably the _single_ most important feature thingy here. Perhaps should be #1 on our priorities in general. I would suggest that we open a separate issue to spec out how we want caching to work.

**Comment by TheCleric** [comment]
Great, I'll break out an issue for 3, add some research and some ideas, and see what the community thinks.

For 1 and 2, what I was thinking is writing some FG and BREF shared code, and then slowly add unit tests and cutover per file, sending a small PR per.

For 4: Looking at the code, I think I see the player ID mapping. Let me know if you would mind me adding something similar for team IDs.

Thanks for the support and feedback. Looking forward to collaborate on this!

**Comment by schorrm** [comment]
I realized I forgot to touch on the Team IDs. Doesn't Retro or Lahman have that? I'll need to double-check.

**Comment by schorrm** [comment]
Looks like all issues here are addressed
