### ISSUE TITLE
Feature: Local caching of data

### ISSUE THREAD

**Issue by TheCleric** [jldbc/pybaseball#87]
This library relies on a set of data sources that are all online, which can be problematic for a few reasons:

1. You may wish to use it offline 

and/or

2. Some of the data source it supports have rate limits (understandably so) that can result in data to not be returned when hit too frequently.

So after discussing with @schorrm in #85 we'd like to add a caching layer that would allow for data to be stored locally for repeat calls. I have some ideas that I will list in further comments, but other suggestions are welcome as well.

**Comment by schorrm** [comment]
So my usual use pattern is one time use of the acquisition functions followed by saving as a CSV / TSV. That's arguably kinda clunky, it making it all 'just work' is arguably the better way.

**Comment by TheCleric** [comment]
One approach would be something along what https://github.com/bdilday/pybbda does. From a cursory analysis of their code base, their approach seems to be, get the data initially, and then reuse that data.

Positives:
- Ensure offline use
Negatives:
- Not as flexible. Rigid process of downloading data before use.

**Comment by schorrm** [comment]
So now on to the meat?
How do we interface with this? Do we have separate functions for downloading and loading from cache, or do we have a unitary function which checks to see if it can pull it from the cache and then executes the query if it can't find it?
We now face the following questions.
1. Where does this go? I suggest `$HOME/.pybaseball/` (we'll need to be careful about the platform independence, e.g. `os.path.join`, not `f'{}/{}'`).
2. How do we track the items in there? We need to standardize a reference form of the query. My initial inclination is t
3. How do we mark an item as invalid in the cache? What are the criteria for an invalid item?
4. Let's say I executed a query or downloaded the data for batters, 2010-2018, independent, no min PA.
I then query batters 2012-2016, independent, min 300 PA. That can be done entirely within the the first file, do we want to make sure that we ID that and get that?

**Comment by TheCleric** [comment]
Another approach is a more passive/silent approach. For example one thing I've done locally is a function wrapper that will cache the data:

```python
def _get_f_hash(f, args, kwargs, by_name_only=False):
    f_hash = f"{f.__name__}" + '' if by_name_only else f"<{f.__hash__()}>"
    
    args_hash = ', '.join([f"{x if isinstance(x, str) else x.__hash__()}" for x in args])
    kwargs_hash = ', '.join(
        [f"{key}={kwargs[key] if isinstance(kwargs[key], str) else kwargs[key].__hash__()}" for key in kwargs.keys()]
    )

    args_key = ', '.join([args_hash, kwargs_hash])

    return f"{f_hash}({args_key})"

class dataframe_file_cache(object):
    default_cache_dir = 'cached_data'

    def __init__(self, by_name_only=True, reset_cache=False, cache_directory=None):
        self.by_name_only = by_name_only
        self.reset_cache = reset_cache
        
        if cache_directory:
            self.cache_directory = cache_directory
        else:
            self.cache_directory = dataframe_file_cache.default_cache_dir
    
    def __call__(self, f):
        def _cached(*args, **kwargs):
            f_hash = _get_f_hash(f, args, kwargs, self.by_name_only)

            csv_path = os.path.join(self.cache_directory, f"{f_hash}.csv")

            if os.path.exists(csv_path):
                data = pd.read_csv(csv_path)
                data.drop(
                    data.columns[data.columns.str.contains('unnamed',case = False)],
                    axis = 1,
                    inplace = True
                )
                return data

            result = f(*args, **kwargs)

            if result is not None and isinstance(result, pd.DataFrame) and not result.empty:
                result.to_csv(csv_path)

            return result
    
        if self.reset_cache:
            self.bust_cache(f)

        return _cached

    def bust_cache(self, f):
        for cache_file in [x for x in os.walk(cache_dir).__next__()[2] if x.startswith(f"{f.__name__}(")]:
            os.remove(os.path.join(self.cache_directory, cache_file))
        self.reset_cache = False

def bust_cache():
    shutil.rmtree(dataframe_file_cache.default_cache_dir)
    os.mkdir(dataframe_file_cache.default_cache_dir)
```

Which would then allow wrapping a function that could get the data if it's not cached, or return the data if cached:

```python
@dataframe_file_cache()
def get_teams():
    return pybaseball.teams()
```

Positives:
- More silent to the user
Negative:
- Chance to request data that is unavailable that could still fail in an online or rate metered scenario.

**Comment by TheCleric** [comment]
Another question that I have that spawns from this discussion is do we continue to go with a library function approach like we have had, or would something like the pybbda library does it with classes that allows a base class to handle all the caching/data retrieval layers. Library function would keep us backwards compatible and eliminate boilerplate implementation code for instantiating classes, but going the class route can lead to cleaner shared code.

**Comment by schorrm** [comment]
I am tempted to say the class route.

**Comment by TheCleric** [comment]
I would be tempted to agree, along with the possibility of having functions in place for backwards compatibility. For example the team_batting function would simply become something like:

```python
def team_batting(start_season, end_season=None, league='all', ind=1):
    return FanGraphs().team_batting(start_season, end_season, league, ind)
```

or even more simply:

```python
_fg = FanGraphs()
team_batting = _fg.team_batting
```

**Comment by schorrm** [comment]
I'm thinking a bit more along the first.
Let's say we took the query <FG team bat 2014-2018, 'all', 1>
So first time that misses. That then should trigger a request, with the DF being stored as a CSV with a filename along the lines of `fg_tm_bat_2014_2018_all_1.csv`
Better yet, if asking for <FG tm bat 2016-2017, 'nl', 1> is found to be queriable against the existing frame in cache and then calculated from there.

**Comment by schorrm** [comment]
@andersonfrailey @TAThor @bdilday @TylerLiu42, I'd love to hear your thoughts since this will be so pervasive. Especially Ben, because of the pybbda

**Comment by TheCleric** [comment]
Obviously, since I wrote it that way in my internal project, I'd prefer a dynamic solution as opposed to a prefetched solution. I'd also recommend starting off with a naive cache and expand it later to support things like filtering cached data to produce the results of an uncached request. Get it working, and then iterate,

**Comment by andersonfrailey** [comment]
I like @TheCleric's idea of adopting the class route. I don't know enough about caching to offer good inputs on how to do it, but I like the idea itself. Like @schorrm I've just been saving data as CSVs if I think I'll need it offline. Re this point though:

>Let's say I executed a query or downloaded the data for batters, 2010-2018, independent, no min PA.
I then query batters 2012-2016, independent, min 300 PA. That can be done entirely within the the first file, do we want to make sure that we ID that and get that?

Is it possible to cache the request made, link that to the data, and build someway to determine if a new request is a subset of an old one? Could we have a "dictionary" with `key:value` pairs that are `request:data` and we format the key to indicate the type of request? In this example we could have
```
"batters_2010-2018_ALL": {path to data}
```
in the cache and then we write the logic to look through the cache, see that we have `batters_2010-2018_ALL`, and then use the cached data for the query?

I'm sure implementing that wouldn't exactly an easy task though.

**Comment by jldbc** [comment]
I'm no expert in caching so my opinion may be uninformed, but I've been resistant to this in the past due to what it would mean for larger file sizes. Some of these requests (a use case I have in mind is requesting several years of statcast events) are large enough where it seems wrong to save the csv by default without a user asking for that.

There are likely thoughtful ways to approach this (only doing it for files below a certain size or making it an argument that defaults to False come to mind). What I'm trying to avoid is silently eating up a bunch of someone's storage without them realizing, since I'm not sure if it's common practice for a package like this one to be storing things to disk unprompted.

Maybe I'm misunderstanding or being too conservative? Thought I'd throw it out there though.

**Comment by TheCleric** [comment]
Those are thoughtful and valid concerns @jldbc. Giving an option to turn it on may be the right approach.

**Comment by schorrm** [comment]
Where it may get a little too conservative, however, is that you end typically with much more stuff downloaded locally, I think. I have several (I honestly don't know how many) copies of the Lahman Databank on my computer by now from this. I have an unholy number of CSVs from FanGraphs scattered throughout.

**Comment by schorrm** [comment]
Things like `download_lahman` going to `$HOME/.pybaseball/` could make good sense even absent a broader caching policy.
What I appreciate in going for a dynamic method is the elegance. I run the first time and it acquires, and then I can rerun the script or the Jupyter notebook verbatim, not changing stuff to `pd.read_csv()` all over the place. So I think it adds value beyond just the storage and speed issues.
Also, if we store in other formats for very large files, we can ameliorate a good deal of the storage issues (parquet etc).

**Comment by TheCleric** [comment]
A few thoughts:

- We could cache with zipped csv files, so that would cut down on the file size
- We could store season level data per season, so a request for multiple seasons data would generate multiple files. And subset data could join the existing files. For example:

Get Team Batting 2015-2019 would store 5 files (2015, 2016, 2017, 2018, 2019)
A further call to get Team Batting for 201602018 would collate the cached 2016, 2017, 2018 data.

**Comment by schorrm** [comment]
From my profiling, I think parquet would be the best choice for the cache. Lowest memory footprint by a big margin, and while it's still slower than feather or pickle it's fast enough, and much faster than CSV.

**Comment by bdilday** [comment]
the lack of caching was actually my original motivation for starting `pybbda`. I decided to make the data download a separate step from data access because I wanted data download to be a really intentional choice by the user. the data frames in `pybbda` are loaded lazily, however. 

the pattern I lean to for accessing the data is to keep small data (Lahman, baseball reference daily WAR) as gzipped csv files that get read into pandas at access time, and larger data, where you'll want to do some filtering and / or aggregations (fangraphs leaderboards, retrosheet events, statcast), as SQL tables.

**Comment by schorrm** [comment]
@bdilday That's really helpful, thank you!
Explicit vs implicit is a design decision, and I don't know if there's a right answer. I suspect there isn't. Perhaps a flexible policy is the way to go? Allow it to be configurable?
And re formats: where it's downloaded as CSV, that'd be one thing. I wonder, given how pleasant working with the parquet from boxball has been, if parquet would let us do everything pretty reasonably here. Memory usage is phenomenal. Speed is very good. Queries are powerful, and we don't a DB engine somewhere (not a ton of lightweight column stores that I know of).

**Comment by TheCleric** [comment]
I think when it comes down to it, for a library like this, explicit vs. implicit comes down to a UX experience. In my opinion, this falls along two lines:

1. Explicit - Give the user more control; more work to set up.
2. Implicit - Make some assumptions for the user up front; less work to set up.

To me, the best of both worlds would probably be something that is implicit but configurable like an explicit model.

I'm also sensitive to the concerns of @jldbc about stealing user's hard drive space without them knowing it, so we could perhaps add an extra, small step to turn it on. I'd propose that by default the system would do nothing different than what it does now: you ask for data, library makes a call, you get data. However, we would prominently put in the docs that if you add a line like:

```python
import pybaseball.caching
```

then we could kick in an implicit cache. We could also have something like a configure function where a power user could configure what they want out of the library (cache directory, cache format, etc.).

I believe this way it's friendly to a user who is not concerned with the caching details, but flexible for users who want finer control.

**Comment by schorrm** [comment]
I was thinking we could have a JSON config in .`.pybaseball/`, `.cache_policy` or something.
We could have a sensible default policy where we max out cache usage at, let's say, 50 MB. And then we could make it configable by script too.

**Comment by jldbc** [comment]
I like both of these suggestions @schorrm @TheCleric. 

How would this behave on something where the file name/source doesn't change, but the content of the file changes? Is there a way to be smart about something like [the Chadwick Bureau Register](https://github.com/chadwickbureau/register)? It seems harder for data where you can't understand its freshness by the dates passed in your initial query. Requesting `schedule_and_record` for the current season sounds similar (the query params don't change from today to tomorrow, but the data does)

**Comment by schorrm** [comment]
I think we'd need to note the date of the cache entry.

**Comment by schorrm** [comment]
Chadwick Bureau probably deserves its own handling, probably based on syncing it with GitHub, with some periodic pulling?

**Comment by TheCleric** [comment]
> How would this behave on something where the file name/source doesn't change, but the content of the file changes?

I'd recommend that we would have a function wrapper for each call we'd like to cache, and in that wrapper you'd be able to specify the volatility of the data. So for that we could have a parameter that says it expires after 24 hours or something like that.

> Chadwick Bureau probably deserves its own handling, probably based on pulling it from GitHub? Saves us having to download from scratch each time, but it's quite volatile.

In that case we can potentially get the latest GitHub commit ref for the file, and if it's changed, redownload it.

**Comment by schorrm** [comment]
I would think a reasonable thing would be to assume that it's volatile but doesn't change more than daily, and just do a Git pull for it the first time it's called that day, and then use it directly subsequently

**Comment by schorrm** [comment]
I'd like to propose the following:
1. Let's start by rolling out a global handling of the Lahman/Chadwick database. There's really zero need to have more than one copy of it per computer, and we've already allowed the temporary / saved option here. Let's change the download location of `download_lahman` from the CWD to some global location (I would suggest `.pybaseball/` on Linux, not sure about Windows).
2. The next obvious candidate would be Statcast. Pitch data doesn't go stale the way current season stuff does. Having stuff be cached there (as Parquet files, I can show the profiling results, it's almost as fast as Feather or Pickle and by far the most space-efficient method), would be a potential benefit. The really big UX improvement, stupid as it may sound, would be that I can run an analysis and the first time have the acquisition call and then not need to shuttle to storage etc, just run the same each time.
3. From there, FanGraphs. This gets really complicated, because we'd want to execute queries across multiple things (granted, `ind=0` and `ind=1` cannot be lumped together, but we would want to allow subsets etc... Perhaps maybe this should borrow from PyBBDA?
4. I think this should be on by default. For people who tinker, they should enjoy that UX improvement (as I described in 2), without tinkering too deeply. For those power users, they should edit the cache_policy.json config or something. I think the way to go about it is to set the max cache size to 50 MB, which will allow us to do at least the 10 or so most recent calls, with parquet, probably even 20, and won't have us borking anybody's storage space.
5. With respect to that, even if we abandon an ambitious plan as described in 3, there is still value to caching for only the exact call.
6. Sans decorator. Should be on by default, unless disabled in cache_policy.json or in a code parameter.

**Comment by TheCleric** [comment]
> I'd like to propose the following:
> 
> 1. Let's start by rolling out a global handling of the Lahman/Chadwick database. There's really zero need to have more than one copy of it per computer, and we've already allowed the temporary / saved option here. Let's change the download location of `download_lahman` from the CWD to some global location (I would suggest `.pybaseball/` on Linux, not sure about Windows).
> 2. The next obvious candidate would be Statcast. Pitch data doesn't go stale the way current season stuff does. Having stuff be cached there (as Parquet files, I can show the profiling results, it's almost as fast as Feather or Pickle and by far the most space-efficient method), would be a potential benefit. The really big UX improvement, stupid as it may sound, would be that I can run an analysis and the first time have the acquisition call and then not need to shuttle to storage etc, just run the same each time.
> 3. From there, FanGraphs. This gets really complicated, because we'd want to execute queries across multiple things (granted, `ind=0` and `ind=1` cannot be lumped together, but we would want to allow subsets etc... Perhaps maybe this should borrow from PyBBDA?
> 4. I think this should be on by default. For people who tinker, they should enjoy that UX improvement (as I described in 2), without tinkering too deeply. For those power users, they should edit the cache_policy.json config or something. I think the way to go about it is to set the max cache size to 50 MB, which will allow us to do at least the 10 or so most recent calls, with parquet, probably even 20, and won't have us borking anybody's storage space.
> 5. With respect to that, even if we abandon an ambitious plan as described in 3, there is still value to caching for only the exact call.
> 6. Sans decorator. Should be on by default, unless disabled in cache_policy.json or in a code parameter.

I have a branch already that does 1, 2, and 6. I also have it turned on for 3 because I feel like a dumb cache is better than no cache (so in agreement with 5).
For 4 I have it presently disabled, but could change that VERY easily.

**Comment by TheCleric** [comment]
A potential implementation for this is in #128

**Comment by schorrm** [comment]
Closing due to being implemented
