### ISSUE TITLE
Any desire for fantasy specific components?

### ISSUE THREAD

**Issue by blacktj** [jldbc/pybaseball#92]
I have a handful of raggedy modules I use for fantasy purposes:
- Most added players yesterday (to see the Anthony Santander, this year or Aquino, last year)
- Two start pitchers (run this every Sunday to see what my options are to add value)

I also use the CBS / Yahoo APIs, which are deprecated, but can still shine through some insights. 

Anyone see any value integrating?

**Comment by jldbc** [comment]
I don't want to open this can of worms - a couple fantasy modules would lead to a ton of requests to expand further into that. I think it would:

1: open up a ton of feature creep in what this package does/is intended for 
2: be thorny to maintain (deprecated APIs, scraping sites that don't want to be scraped, lead to supporting a long tail of fantasy providers vs. the relatively small number of data providers we're exposed to currently)

That's my first take. Do others have thoughts? I think if we do support fantasy, it should be a broader conversation about which sites we support and how that's designed (e.g. having more complete support for one or two given fantasy sites might be more defensible than supporting the whole long tail of sites/reports/data that exist in that world)

**Comment by schorrm** [comment]
I don't see value in integrating with deprecated APIs. I would prefer for something like this to focus on stable stuff. Things like two start pitchers aren't of much interest to baseball analytics outside that context.

**Comment by schorrm** [comment]
Closing for lack of other interest.
