### ISSUE TITLE
Add Seamheads Data

### ISSUE THREAD

**Issue by schorrm** [jldbc/pybaseball#93]
Seamheads has the best Negro League data. By far.

**Comment by Am3ra** [comment]
What would be required for this change?

**Comment by schorrm** [comment]
Roughly mirroring the stuff we have for FG / Bref. Just the legwork of getting the correct URLs, parsing, etc

**Comment by TheCleric** [comment]
If we finish the FG cutover to the new parser, I think it could be made a bit more generic to support new data sources like this one fairly easily as they are both HTML table -> DataFrame extractions.

**Comment by schorrm** [comment]
Everything but Statcast is HTML table to DF extractions.

**Comment by schorrm** [comment]
Closing due to BRef 😄
