### ISSUE TITLE
Marcel projections (pybbda integration)

### ISSUE THREAD

**Issue by bdilday** [jldbc/pybaseball#98]
after talking with @schorrm we think it makes sense to pull some of the features from [pybbda](https://github.com/bdilday/pybbda) into this library. The first one I want to start with is marcel projections. this issue is for any discussion we may want to have around this feature. See https://github.com/jldbc/pybaseball/pull/99

**Comment by schorrm** [comment]
One ring to unite **ALL** the baseball libraries for Python

**Comment by bdilday** [comment]
a design question - do we want to export these at the top-level, i.e. to be able to do `from pybaseball import  MarcelProjectionsBatting`? Personally I'm ok with / prefer the more specific `from pybaseball.analysis.projections import MarcelProjectionsBatting`, however I don't have too strong an opinion

**Comment by TheCleric** [comment]
Only thing I would mention is this:

It seems like thusfar, the pybaseball library is focused on being a data retriever (Lahman, FanGraphs, BBRef, etc).

This would be a move into adding more of a data analysis tool. I'm not saying that I'm against that, just noting the shift in focus.

If we decide that shift is fine, I agree with @bdilday that putting it into it own section (such as `pybaseball.analysis`) would be ideal.

**Comment by jldbc** [comment]
I think specifying `analysis` is helpful, especially given that this is a new category of function for the package. 

Ideally I'd like to move this whole thing in a direction where a user can guess most or all of the import path + function without spending much time reading code or documentation, so things like an `pybaseball.analysis` are a good start. 

There's probably a more helpful way of organizing the data collection functions in a similar way (e.g. `from pybaseball.datasources.[fangraphs or bbref] import batting_stats`). That's definitely a separate issue though.

**Comment by schorrm** [comment]
Closing, merged in #99 .
